### PR TITLE
a

### PR DESCRIPTION
**Pull request by Ueaj-Kerman**

### CODE REVIEW

**Comment by ghost** [comment]
a

**Comment by ramidzkh** [comment]
no

**Review by ramidzkh — APPROVED** [review]
i dont approve

**Review by ramidzkh — CHANGES_REQUESTED** [review]
image
useless pr

**Review by LemmaEOF — CHANGES_REQUESTED** [review]
- crusty and brug are identical
- pufferfish and jazzpufferfish are identical
- thonkjang and eula are identical
- many emoji are non-square and I don't trust minecraft to be ok with that
- your memes are bad and you should feel bad

**Comment by Ueaj-Kerman** [comment]
Iritat

**Comment by bluebear94** [comment]
where are :voldethonk:, :eclipsethonk:, :intellithonk:, :hhm:, and :mixinthink:

**Review by YTG1234 — CHANGES_REQUESTED** [review]
I agree with Boundary's first 3 points. I also agree with bluebear.

**Pull request closed without merging**
